package com.tns.seocrawler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CrawlLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlLogAllPropertiesEquals(CrawlLog expected, CrawlLog actual) {
        assertCrawlLogAutoGeneratedPropertiesEquals(expected, actual);
        assertCrawlLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlLogAllUpdatablePropertiesEquals(CrawlLog expected, CrawlLog actual) {
        assertCrawlLogUpdatableFieldsEquals(expected, actual);
        assertCrawlLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlLogAutoGeneratedPropertiesEquals(CrawlLog expected, CrawlLog actual) {
        assertThat(actual)
            .as("Verify CrawlLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlLogUpdatableFieldsEquals(CrawlLog expected, CrawlLog actual) {
        assertThat(actual)
            .as("Verify CrawlLog relevant properties")
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCrawledAt()).as("check crawledAt").isEqualTo(expected.getCrawledAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlLogUpdatableRelationshipsEquals(CrawlLog expected, CrawlLog actual) {
        assertThat(actual)
            .as("Verify CrawlLog relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
