package com.tns.seocrawler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteSettingAllPropertiesEquals(SiteSetting expected, SiteSetting actual) {
        assertSiteSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteSettingAllUpdatablePropertiesEquals(SiteSetting expected, SiteSetting actual) {
        assertSiteSettingUpdatableFieldsEquals(expected, actual);
        assertSiteSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteSettingAutoGeneratedPropertiesEquals(SiteSetting expected, SiteSetting actual) {
        assertThat(actual)
            .as("Verify SiteSetting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteSettingUpdatableFieldsEquals(SiteSetting expected, SiteSetting actual) {
        assertThat(actual)
            .as("Verify SiteSetting relevant properties")
            .satisfies(a -> assertThat(a.getSiteTitle()).as("check siteTitle").isEqualTo(expected.getSiteTitle()))
            .satisfies(a -> assertThat(a.getSiteDescription()).as("check siteDescription").isEqualTo(expected.getSiteDescription()))
            .satisfies(a -> assertThat(a.getSiteKeywords()).as("check siteKeywords").isEqualTo(expected.getSiteKeywords()))
            .satisfies(a -> assertThat(a.getGaTrackingId()).as("check gaTrackingId").isEqualTo(expected.getGaTrackingId()))
            .satisfies(a -> assertThat(a.getBannerTop()).as("check bannerTop").isEqualTo(expected.getBannerTop()))
            .satisfies(a -> assertThat(a.getBannerSidebar()).as("check bannerSidebar").isEqualTo(expected.getBannerSidebar()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteSettingUpdatableRelationshipsEquals(SiteSetting expected, SiteSetting actual) {
        assertThat(actual)
            .as("Verify SiteSetting relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
