package com.tns.seocrawler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAllPropertiesEquals(Source expected, Source actual) {
        assertSourceAutoGeneratedPropertiesEquals(expected, actual);
        assertSourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAllUpdatablePropertiesEquals(Source expected, Source actual) {
        assertSourceUpdatableFieldsEquals(expected, actual);
        assertSourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceAutoGeneratedPropertiesEquals(Source expected, Source actual) {
        assertThat(actual)
            .as("Verify Source auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceUpdatableFieldsEquals(Source expected, Source actual) {
        assertThat(actual)
            .as("Verify Source relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBaseUrl()).as("check baseUrl").isEqualTo(expected.getBaseUrl()))
            .satisfies(a -> assertThat(a.getListUrl()).as("check listUrl").isEqualTo(expected.getListUrl()))
            .satisfies(a -> assertThat(a.getListItemSelector()).as("check listItemSelector").isEqualTo(expected.getListItemSelector()))
            .satisfies(a -> assertThat(a.getLinkAttr()).as("check linkAttr").isEqualTo(expected.getLinkAttr()))
            .satisfies(a -> assertThat(a.getTitleSelector()).as("check titleSelector").isEqualTo(expected.getTitleSelector()))
            .satisfies(a -> assertThat(a.getContentSelector()).as("check contentSelector").isEqualTo(expected.getContentSelector()))
            .satisfies(a -> assertThat(a.getThumbnailSelector()).as("check thumbnailSelector").isEqualTo(expected.getThumbnailSelector()))
            .satisfies(a -> assertThat(a.getAuthorSelector()).as("check authorSelector").isEqualTo(expected.getAuthorSelector()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceUpdatableRelationshipsEquals(Source expected, Source actual) {
        assertThat(actual)
            .as("Verify Source relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
